ThisBuild / organization := "io.github.jpablo"
ThisBuild / version := "0.1.0-SNAPSHOT"
ThisBuild / scalaVersion := "3.8.1"

lazy val munitVersion = "1.1.1"
lazy val kyoVersion   = "1.0.0-RC2"

lazy val kyoSchemaDeps = Seq(
  "io.getkyo" %% "kyo-data"   % kyoVersion,
  "io.getkyo" %% "kyo-schema" % kyoVersion
)

lazy val commonSettings = Seq(
  scalacOptions ++= Seq(
    "-deprecation",
    "-feature",
    "-unchecked"
  )
)

lazy val root = (project in file("."))
  .aggregate(
    core,
    typed,
    lm,
    adapters,
    programs,
    evaluate,
    optimize,
    streaming,
    examples,
    prototypeZioBlocks
  )
  .settings(commonSettings)
  .settings(
    name := "dspy4s",
    publish / skip := true
  )

lazy val core = (project in file("modules/core"))
  .settings(commonSettings)
  .settings(name := "dspy4s-core")
  .settings(
    libraryDependencies += "org.scalameta" %% "munit" % munitVersion % Test,
    Test / parallelExecution := false
  )

// Typed signatures layer. kyo-schema is used in production as the structured
// codec backend behind dspy4s's FieldCodec boundary. kyo-data is explicit
// because kyo-schema's Structure.Value tree and test Record probes use its
// collection/data primitives.
//
// Migration in progress: zio-blocks-schema is being introduced as the
// replacement for kyo-schema; both libs coexist during the migration.
lazy val typed = (project in file("modules/typed"))
  .dependsOn(core)
  .settings(commonSettings)
  .settings(name := "dspy4s-typed")
  .settings(
    libraryDependencies ++= kyoSchemaDeps ++ Seq(
      "dev.zio"       %% "zio-blocks-schema" % "0.0.40",
      "org.scalameta" %% "munit"             % munitVersion % Test
    )
  )

lazy val lm = (project in file("modules/lm"))
  .dependsOn(core)
  .settings(commonSettings)
  .settings(name := "dspy4s-lm")
  .settings(
    libraryDependencies ++= Seq(
      "org.scalameta" %% "munit" % munitVersion % Test,
      "com.lihaoyi" %% "ujson" % "4.0.2",
      "io.github.cdimascio" % "dotenv-java" % "3.2.0" % Test
    ),
    Test / fork := true,
    Test / javaOptions += "-Dfile.encoding=UTF-8"
  )

lazy val adapters = (project in file("modules/adapters"))
  .dependsOn(core, lm)
  .settings(commonSettings)
  .settings(name := "dspy4s-adapters")
  .settings(
    libraryDependencies ++= Seq(
      "org.scalameta" %% "munit" % munitVersion % Test,
      "com.lihaoyi" %% "ujson" % "4.0.2",
      "org.scala-lang.modules" %% "scala-xml" % "2.3.0"
    )
  )

lazy val programs = (project in file("modules/programs"))
  .dependsOn(core, lm, adapters, typed)
  .settings(commonSettings)
  .settings(name := "dspy4s-modules")
  .settings(
    libraryDependencies ++= kyoSchemaDeps :+
      ("org.scalameta" %% "munit" % munitVersion % Test)
  )

lazy val evaluate = (project in file("modules/evaluate"))
  .dependsOn(core, programs)
  .settings(commonSettings)
  .settings(name := "dspy4s-evaluate")
  .settings(
    libraryDependencies ++= Seq(
      "org.scalameta" %% "munit" % munitVersion % Test,
      "com.lihaoyi" %% "ujson" % "4.0.2"
    )
  )

lazy val optimize = (project in file("modules/optimize"))
  .dependsOn(core, programs, evaluate)
  .settings(commonSettings)
  .settings(name := "dspy4s-optimize")
  .settings(
    libraryDependencies += "org.scalameta" %% "munit" % munitVersion % Test
  )

lazy val streaming = (project in file("modules/streaming"))
  .dependsOn(core, lm, adapters, programs)
  .settings(commonSettings)
  .settings(name := "dspy4s-streaming")
  .settings(
    libraryDependencies += "org.scalameta" %% "munit" % munitVersion % Test,
    // Fork so `.env`-backed envVars (loaded by DotEnvLoader) reach the test
    // JVM — required by StreamingLiveSuite to read OPENAI_API_KEY.
    Test / fork := true,
    Test / javaOptions += "-Dfile.encoding=UTF-8"
  )

// Scaffold + translations of every code snippet that appears in the upstream
// Python DSPy documentation under docs/docs/. Each .scala file mirrors a .md
// file 1:1 and links back to the source. Scaffolds are generated by
// modules/examples/tools/scaffold.py.
lazy val examples = (project in file("modules/examples"))
  .dependsOn(core, lm, adapters, programs, typed, evaluate, optimize, streaming)
  .settings(commonSettings)
  .settings(name := "dspy4s-examples")
  .settings(
    publish / skip := true,
    libraryDependencies ++= kyoSchemaDeps
  )

// Throwaway experiment: evaluate whether zio-blocks Schema could replace
// kyo-schema + our Shape / FieldCodec glue. Self-contained, no `dependsOn`
// edges to the main codebase, so deleting this directory removes the dep
// cleanly.
lazy val prototypeZioBlocks = (project in file("prototype/zio-blocks"))
  .settings(commonSettings)
  .settings(
    name := "dspy4s-prototype-zio-blocks",
    publish / skip := true,
    libraryDependencies ++= Seq(
      "dev.zio"        %% "zio-blocks-schema" % "0.0.40",
      "org.scalameta"  %% "munit"             % munitVersion % Test
    )
  )
