ThisBuild / organization := "io.github.jpablo"
ThisBuild / version := "0.1.0-SNAPSHOT"
ThisBuild / scalaVersion := "3.8.4"

// Disable sbt's built-in BSP server: IntelliJ imports this project via its native sbt importer (not BSP),
// and nothing else consumes BSP here, so the auto-generated `.bsp/sbt.json` is just noise. This stops sbt
// from re-creating it on every run.
Global / bspEnabled := false

lazy val munitVersion     = "1.3.1"
lazy val zioBlocksVersion = "0.0.41"
lazy val ujsonVersion     = "4.4.3"
lazy val dotenvVersion    = "3.2.0"
lazy val scalaXmlVersion  = "2.4.0"

lazy val commonSettings = Seq(
  scalacOptions ++= Seq(
    "-deprecation",
    "-feature",
    "-unchecked",
    "-language:strictEquality",
    "-Werror",
    "-Wunused:all",
    "-Wvalue-discard",
    "-Wnonunit-statement",
    "-Wimplausible-patterns",
    "-Wsafe-init",
    "-Wshadow:all",
    "-Wenum-comment-discard",
    "-Wrecurse-with-default",
    "-Wwrong-arrow",
    "-explain"
  )
)

lazy val root = (project in file("."))
  .aggregate(
    core,
    typed,
    lm,
    adapters,
    programs,
    evaluate,
    optimize,
    streaming,
    examples
  )
  .settings(commonSettings)
  .settings(
    name := "dspy4s",
    publish / skip := true
  )

// `core` owns the contract layer that everything else builds on. We pull in
// zio-blocks-schema here because `DynamicValue` is the spine type carried
// through `Example.values`, `ProgramCall.inputs`, `DynamicPrediction.values`,
// and `ParsedOutput.values` — the codec intermediate shared by adapters,
// programs, evaluate, and the typed surface.
lazy val core = (project in file("modules/core"))
  .settings(commonSettings)
  .settings(name := "dspy4s-core")
  .settings(
    libraryDependencies ++= Seq(
      "dev.zio"       %% "zio-blocks-schema" % zioBlocksVersion,
      "org.scalameta" %% "munit"             % munitVersion % Test
    ),
    Test / parallelExecution := false
  )

// Typed signatures layer. zio-blocks-schema is the structured codec backend
// behind dspy4s's FieldCodec boundary (see ZioSchemaCodec) and provides the
// Schema typeclass that `Signature.derived` / `Shape.derived` summon.
lazy val typed = (project in file("modules/typed"))
  .dependsOn(core)
  .settings(commonSettings)
  .settings(name := "dspy4s-typed")
  .settings(
    libraryDependencies ++= Seq(
      "dev.zio"       %% "zio-blocks-schema" % zioBlocksVersion,
      "org.scalameta" %% "munit"             % munitVersion % Test
    )
  )

lazy val lm = (project in file("modules/lm"))
  .dependsOn(core)
  .settings(commonSettings)
  .settings(name := "dspy4s-lm")
  .settings(
    libraryDependencies ++= Seq(
      "org.scalameta" %% "munit" % munitVersion % Test,
      "com.lihaoyi" %% "ujson" % ujsonVersion,
      "io.github.cdimascio" % "dotenv-java" % dotenvVersion % Test
    ),
    Test / fork := true,
    Test / javaOptions += "-Dfile.encoding=UTF-8"
  )

lazy val adapters = (project in file("modules/adapters"))
  .dependsOn(core, lm)
  .settings(commonSettings)
  .settings(name := "dspy4s-adapters")
  .settings(
    libraryDependencies ++= Seq(
      "org.scalameta" %% "munit" % munitVersion % Test,
      "com.lihaoyi" %% "ujson" % ujsonVersion,
      "org.scala-lang.modules" %% "scala-xml" % scalaXmlVersion
    )
  )

lazy val programs = (project in file("modules/programs"))
  .dependsOn(core, lm, adapters, typed)
  .settings(commonSettings)
  .settings(name := "dspy4s-modules")
  .settings(
    libraryDependencies += "org.scalameta" %% "munit" % munitVersion % Test
  )

lazy val evaluate = (project in file("modules/evaluate"))
  .dependsOn(core, programs)
  .settings(commonSettings)
  .settings(name := "dspy4s-evaluate")
  .settings(
    libraryDependencies ++= Seq(
      "org.scalameta" %% "munit" % munitVersion % Test,
      "com.lihaoyi" %% "ujson" % ujsonVersion
    )
  )

lazy val optimize = (project in file("modules/optimize"))
  .dependsOn(core, programs, evaluate)
  .settings(commonSettings)
  .settings(name := "dspy4s-optimize")
  .settings(
    libraryDependencies += "org.scalameta" %% "munit" % munitVersion % Test
  )

lazy val streaming = (project in file("modules/streaming"))
  .dependsOn(core, lm, adapters, programs)
  .settings(commonSettings)
  .settings(name := "dspy4s-streaming")
  .settings(
    libraryDependencies += "org.scalameta" %% "munit" % munitVersion % Test,
    // Fork so `.env`-backed envVars (loaded by DotEnvLoader) reach the test
    // JVM — required by StreamingLiveSuite to read OPENAI_API_KEY.
    Test / fork := true,
    Test / javaOptions += "-Dfile.encoding=UTF-8"
  )

// Scaffold + translations of every code snippet that appears in the upstream
// Python DSPy documentation under docs/docs/. Each .scala file mirrors a .md
// file 1:1 and links back to the source. Scaffolds are generated by
// modules/examples/tools/scaffold.py.
lazy val examples = (project in file("modules/examples"))
  .dependsOn(core, lm, adapters, programs, typed, evaluate, optimize, streaming)
  .settings(commonSettings)
  .settings(name := "dspy4s-examples")
  .settings(
    publish / skip := true
  )

